"""Curated clinic workflow catalog for a general-surgery service.

Entries are deliberately generic. Local governance should map them to the
hospital formulary, coding system, laboratory catalogue, and approved templates.
No default medication dose is generated by the software.
"""

APPOINTMENT_TYPES = [
    "New consultation",
    "Follow-up visit",
    "Post-operative visit",
    "Pre-operative review",
    "Wound review",
    "Dressing change",
    "Drain review / removal",
    "Suture / staple removal",
    "Results review",
    "Teleconsultation",
    "Emergency walk-in",
]

APPOINTMENT_STATUSES = [
    "Scheduled", "Confirmed", "Checked-in", "Waiting", "With doctor",
    "Completed", "No-show", "Cancelled", "Rescheduled",
]

ENCOUNTER_TYPES = [
    "New consultation", "Follow-up", "Post-operative", "Pre-operative",
    "Wound care", "Results review", "Teleconsultation", "Emergency assessment",
]

FOLLOWUP_TYPES = [
    "Post-operative clinic", "Wound review", "Suture/staple removal",
    "Drain review/removal", "Pathology review", "Telephone review",
    "Return-to-work review", "Long-term surveillance",
]

COMMON_MEDICATIONS = [
    "Paracetamol", "Ibuprofen", "Diclofenac", "Ketorolac", "Celecoxib",
    "Tramadol", "Morphine", "Ondansetron", "Metoclopramide",
    "Omeprazole", "Pantoprazole", "Famotidine",
    "Amoxicillin/clavulanate", "Cefazolin", "Ceftriaxone", "Cefuroxime",
    "Metronidazole", "Piperacillin/tazobactam", "Meropenem",
    "Enoxaparin", "Unfractionated heparin",
    "Lactulose", "Polyethylene glycol", "Senna", "Docusate",
    "Oral rehydration solution", "Normal saline", "Ringer's lactate",
    "Other medication",
]

DOSAGE_FORMS = ["Tablet", "Capsule", "Syrup", "Suspension", "Injection", "Infusion", "Suppository", "Cream/Ointment", "Drops", "Other"]
ROUTES = ["Oral", "IV", "IM", "SC", "Rectal", "Topical", "Sublingual", "Inhaled", "Other"]
FREQUENCIES = ["Once daily", "Twice daily", "Three times daily", "Four times daily", "Every 4 hours", "Every 6 hours", "Every 8 hours", "Every 12 hours", "At night", "As required (PRN)", "Other"]

INVESTIGATION_CATEGORIES = ["Laboratory", "Radiology", "Pathology", "Endoscopy", "Cardiology", "Anesthesia", "Blood bank", "Referral", "Other"]

COMMON_INVESTIGATIONS = {
    "Laboratory": [
        "CBC", "CRP", "ESR", "Urea and electrolytes", "Creatinine", "Liver function tests",
        "Coagulation profile", "INR", "Blood glucose", "HbA1c", "Amylase", "Lipase",
        "Pregnancy test", "Urinalysis", "Blood culture", "Wound culture", "Other laboratory test",
    ],
    "Radiology": [
        "Ultrasound abdomen", "Ultrasound pelvis", "Ultrasound breast", "Ultrasound thyroid",
        "Chest X-ray", "Abdominal X-ray", "CT abdomen/pelvis", "CT chest", "CT angiography",
        "MRI", "MRCP", "Mammography", "Other imaging",
    ],
    "Pathology": ["Histopathology", "Cytology / FNA", "Frozen section", "Immunohistochemistry", "Other pathology"],
    "Endoscopy": ["Upper GI endoscopy", "Colonoscopy", "Flexible sigmoidoscopy", "ERCP", "Other endoscopy"],
    "Cardiology": ["ECG", "Echocardiography", "Cardiology assessment", "Stress test"],
    "Anesthesia": ["Pre-anesthesia assessment"],
    "Blood bank": ["Group and screen", "Crossmatch", "Prepare blood products"],
    "Referral": ["Nutrition", "Physiotherapy", "Wound care", "Endocrinology", "Oncology", "Other referral"],
    "Other": ["Other request"],
}

CLINIC_TEMPLATES = {
    "General abdominal complaint": {
        "exam": "General condition:\nAbdominal inspection:\nPalpation:\nPercussion:\nAuscultation:\nHernial orifices:\nDigital rectal examination when indicated:",
        "plan": "Investigations:\nInitial management:\nSafety-net advice:\nFollow-up:",
    },
    "Hernia": {
        "exam": "Site and side:\nReducibility:\nCough impulse:\nTenderness:\nSkin changes:\nContralateral side:\nScrotal examination when indicated:",
        "plan": "Watchful waiting vs repair discussed:\nProcedure options:\nRisk optimization:\nPre-operative work-up:",
    },
    "Gallstone disease": {
        "exam": "RUQ tenderness:\nMurphy sign:\nJaundice:\nFever/sepsis features:\nAbdominal examination:",
        "plan": "Ultrasound/LFT review:\nCBD stone risk:\nAcute vs elective pathway:\nSafety-net advice:",
    },
    "Breast complaint": {
        "exam": "Inspection:\nPalpable lesion (site/size/mobility):\nSkin/nipple changes:\nAxillary nodes:\nContralateral breast:",
        "plan": "Triple assessment:\nImaging:\nBiopsy/cytology:\nMDT/referral plan:",
    },
    "Thyroid complaint": {
        "exam": "Neck inspection:\nNodule/goitre:\nMovement with swallowing:\nCervical nodes:\nVoice:\nCompressive symptoms:",
        "plan": "TSH/thyroid profile:\nUltrasound/TIRADS:\nFNA indication:\nSurgical/endocrine plan:",
    },
    "Anorectal complaint": {
        "exam": "Perianal inspection:\nDigital rectal examination:\nProctoscopy/anoscopy when appropriate:\nBleeding/prolapse/fissure/fistula findings:",
        "plan": "Conservative treatment:\nEndoscopic assessment indication:\nProcedure options:\nFollow-up:",
    },
    "Post-operative review": {
        "exam": "General condition:\nPain score:\nWound:\nDrain:\nOral intake:\nBowel/urinary function:\nMobility:\nComplication screen:",
        "plan": "Medication reconciliation:\nWound/drain plan:\nPathology review:\nActivity and diet:\nNext follow-up:",
    },
}
